<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Table Parameters given in the question -->
  <xacro:macro name="table" params="prefix parent *origin">

    <!-- Table Dimensions -->
    <xacro:property name="table_width" value="1" />
    <xacro:property name="table_height" value="1" />
    <xacro:property name="table_length" value="2" />
    <xacro:property name="table_thickness" value="0.05" />

    <!-- Given Constraints -->
    <xacro:property name="leg_length" value="${table_height - table_thickness}" />
    <xacro:property name="leg_radius" value="0.05" />

    <!-- Joint connecting table top to frame -->
    <joint name="${prefix}table_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}top"/>
    </joint>

    <!-- Table top link -->
    <link name="${prefix}top">
      <visual>
        <!-- top frame is centered on the TOP surface -->
        <origin xyz="0 0 ${-table_thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${table_length} ${table_width} ${table_thickness}"/>
        </geometry>
        <material name="brown"/>
      </visual>
    </link>

    <!-- Tangent to the sides -->
    <xacro:property name="x_off" value="${table_length/2 - leg_radius}" />
    <xacro:property name="y_off" value="${table_width/2 - leg_radius}" />

    <!-- Leg macro -->
    <xacro:macro name="leg" params="name x y">

      <link name="${prefix}${name}">
        <visual>
          <!-- leg frame is at TOP of leg -->
          <origin xyz="0 0 ${-leg_length/2}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>
          </geometry>
          <material name="light_grey"/>
        </visual>
      </link>

      <joint name="${prefix}${name}_joint" type="fixed">
        <parent link="${prefix}top"/>
        <child link="${prefix}${name}"/>
        <!-- put leg TOP at underside of tabletop -->
        <origin xyz="${x} ${y} ${-table_thickness}" rpy="0 0 0"/>
      </joint>

    </xacro:macro>

    <!-- Four legs: tangent to sides and fully under top -->
    <xacro:leg name="leg1" x="${ x_off}"  y="${ y_off}"/>
    <xacro:leg name="leg2" x="${ x_off}"  y="${-y_off}"/>
    <xacro:leg name="leg3" x="${-x_off}"  y="${ y_off}"/>
    <xacro:leg name="leg4" x="${-x_off}"  y="${-y_off}"/>

  </xacro:macro>

</robot>

